//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropDownFilterDataAccessSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificate
    {
        public string empid { get; set; }
        public string cid { get; set; }
        public Nullable<System.DateTime> datecompleted { get; set; }
    
        public virtual course course { get; set; }
        public virtual employee employee { get; set; }
    }
}
