//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropDownFilterDataAccessSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyData
    {
        public int companyId { get; set; }
        public string CompanyName { get; set; }
        public string Program { get; set; }
        public string Country { get; set; }
        public string Job_Description { get; set; }
    }
}
