//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DropDownFilterDataAccessSQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class section8Entities : DbContext
    {
        public section8Entities()
            : base("name=section8Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<certificate> certificates { get; set; }
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<DropDownFilter> DropDownFilters { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<JobDescriptionData> JobDescriptionDatas { get; set; }
        public virtual DbSet<orderproduct> orderproducts { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<part> parts { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<dept> depts { get; set; }
        public virtual DbSet<CompanyData> CompanyDatas { get; set; }
    }
}
